### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by KurenaiRyu** [Ivanlon30000/PlayniteBangumiMetadata#1]
如题，配置了token跟没配置token都会报这个错误
![error](https://user-images.githubusercontent.com/18627047/213900155-39933c3c-06be-43d4-b057-ad908cf49d7c.jpg)

**Comment by Ivanlon30000** [comment]
尝试填写Access Token后重启Playnite

或者更新到v1.1.0
[Release](https://github.com/Ivanlon30000/PlayniteBangumiMetadata/releases/tag/v1.1.0)

**Comment by KurenaiRyu** [comment]
可以了
