### ISSUE TITLE
下载资料数据失败:Error getting value from'Name' onBangumi.Models.PlayniteSubject'

### ISSUE THREAD

**Issue by Joackk** [Ivanlon30000/PlayniteBangumiMetadata#2]
**描述问题**
令牌已经配置，网络正常。搜索到目标后，点击选择提示：下载资料数据失败，尝试了几个galgame都有这个问题
![7c2138fc3a0d01329eb4ef8c7265308b](https://github.com/Ivanlon30000/PlayniteBangumiMetadata/assets/45162558/4bab9329-7b56-4da7-8f70-fd82e9304603)

**复现步骤**
搜索天色幻想岛，ran'h然后点击选择，出现上述错误
![image](https://github.com/Ivanlon30000/PlayniteBangumiMetadata/assets/45162558/16c50327-ff32-4a36-9be7-d4ac341e6208)

**期望表现**
正常将下载

**截图**

**Log文件**  
10-03 19:14:19.773|DEBUG|Bangumi#Bangumi:invoke GetMetadataProvider:Playnite.SDK.Plugins.MetadataRequestOptions
10-03 19:14:19.773|DEBUG|Bangumi#Bangumi:new BangumiProvider
10-03 19:14:19.773|DEBUG|Bangumi#Bangumi:invoke GetName
10-03 19:14:19.773|DEBUG|Bangumi#Bangumi:invoke GetAvailableFields
10-03 19:14:19.773|DEBUG|Bangumi#Bangumi:invoke GetBangumiMetadata
10-03 19:14:19.792|DEBUG|Bangumi#Bangumi:Search '天色幻想岛'
10-03 19:14:19.792|DEBUG|Bangumi#Bangumi:Get /search/subject/%E5%A4%A9%E8%89%B2%E5%B9%BB%E6%83%B3%E5%B2%9B
10-03 19:14:20.764|DEBUG|Bangumi#Bangumi:Search result: [65223,117925,233713,121606,319972,208259,3903,662,378680]
10-03 19:14:23.100|DEBUG|Bangumi#Bangumi:selected item: PlayniteSearchOption{65223, 天色＊アイルノーツ (天色幻想岛), "鷺ノ森透"は悩んでいた。大学を卒業し、教師として就職したものの、このまま教師を続けていくべきかどうか、を。そんな迷いを持つ彼のもとに、ある日一つの誘いが舞い込む。それは青天の霹靂と呼ぶべきもので——...}
10-03 19:14:23.100|DEBUG|Bangumi#Bangumi:invoke GetSubjectById(65223)
10-03 19:14:23.100|DEBUG|Bangumi#Bangumi:Get /v0/subjects/65223
10-03 19:14:23.527|DEBUG|Bangumi#Bangumi:Subject:

**Comment by Ivanlon30000** [comment]
感谢反馈。
修改AccessToken后需要重启Playnite才能生效（v1.2.0版本及之前）。
在没有配置AccessToken时有的条目可以被搜索到，但是获取详情时会404，这可能是导致这个Issue的原因。

已经更新了[v1.3.0](https://github.com/Ivanlon30000/PlayniteBangumiMetadata/releases/tag/v1.3.0)版本，优化了AccessToken的使用逻辑，可以在保存设置之后立即生效。

**Comment by Joackk** [comment]
> 感谢反馈。 修改AccessToken后需要重启Playnite才能生效（v1.2.0版本及之前）。 在没有配置AccessToken时有的条目可以被搜索到，但是获取详情时会404，这可能是导致这个Issue的原因。
> 
> 已经更新了[v1.3.0](https://github.com/Ivanlon30000/PlayniteBangumiMetadata/releases/tag/v1.3.0)版本，优化了AccessToken的使用逻辑，可以在保存设置之后立即生效。

这个似乎是因为注册时长原因，不是插件问题，似乎是要注册满一个月才能浏览18x的栏目
