### ISSUE TITLE
BANGUMI简介无法刮削

### ISSUE THREAD

**Issue by X012C** [Ivanlon30000/PlayniteBangumiMetadata#5]
日志：
``24-07 21:39:50.998|DEBUG|Bangumi#Bangumi:invoke GetMetadataProvider:Playnite.SDK.Plugins.MetadataRequestOptions
24-07 21:39:51.002|DEBUG|Bangumi#Bangumi:new BangumiProvider
24-07 21:39:51.002|DEBUG|Bangumi#Bangumi:invoke GetAvailableFields
24-07 21:39:51.002|DEBUG|Bangumi#Bangumi:invoke GetBangumiMetadata
24-07 21:39:51.067|DEBUG|Bangumi#Bangumi:Search '麻呂の患者はガテン系（麻吕的患者是蓝领）'
24-07 21:39:51.067|DEBUG|Bangumi#Bangumi:Get /search/subject/%E9%BA%BB%E5%91%82%E3%81%AE%E6%82%A3%E8%80%85%E3%81%AF%E3%82%AC%E3%83%86%E3%83%B3%E7%B3%BB%EF%BC%88%E9%BA%BB%E5%90%95%E7%9A%84%E6%82%A3%E8%80%85%E6%98%AF%E8%93%9D%E9%A2%86%EF%BC%89
24-07 21:39:51.968|DEBUG|Bangumi#Bangumi:Search result: [70716,78352,147297]
24-07 21:39:54.034|DEBUG|Bangumi#Bangumi:selected item: PlayniteSearchOption{70716, 麻呂の患者はガテン系（麻吕的患者是蓝领）, }
24-07 21:39:54.034|DEBUG|Bangumi#Bangumi:invoke GetSubjectById(70716)
24-07 21:39:54.034|DEBUG|Bangumi#Bangumi:Get /v0/subjects/70716
24-07 21:39:54.896|DEBUG|Bangumi#Bangumi:Subject: {"id":70716,"type":4,"name":"麻呂の患者はガテン系","nameCn":"麻吕的患者是蓝领","summary":"","nsfw":true,"locked":false,"date":"2013-04-25","platform":"游戏","images":{"small":"https://lain.bgm.tv/r/200/pic/cover/l/d6/c2/70716_Z0uex.jpg","grid":"https://lain.bgm.tv/r/100/pic/cover/l/d6/c2/70716_Z0uex.jpg","large":"https://lain.bgm.tv/pic/cover/l/d6/c2/70716_Z0uex.jpg","medium":"https://lain.bgm.tv/r/800/pic/cover/l/d6/c2/70716_Z0uex.jpg","common":"https://lain.bgm.tv/r/400/pic/cover/l/d6/c2/70716_Z0uex.jpg"},"textInfobox":{"中文名":"麻吕的患者是蓝领","游玩人数":"1","发行日期":"2013-04-25","ブランド":"エルフ","原画":"坂上海","シナリオ":"土天冥海"},"listInfoBox":{},"volumes":0,"eps":0,"totalEpisodes":0,"rating":{"rank":4290,"total":141,"count":{"1":0,"2":0,"3":1,"4":4,"5":13,"6":36,"7":51,"8":28,"9":4,"10":4},"score":6.8},"collection":{"on_hold":14,"dropped":6,"wish":158,"collect":196,"doing":10},"tags":[{"name":"ELF","count":61},{"name":"NTR","count":53},{"name":"galgame","count":47},{"name":"土天冥海","count":44},{"name":"拔作","count":32},{"name":"动态CG","count":31},{"name":"NTL","count":19},{"name":"2013","count":15},{"name":"人妻","count":15},{"name":"R18","count":11},{"name":"PC","count":10},{"name":"GAL","count":7},{"name":"生肉","count":4},{"name":"ADV","count":4},{"name":"机翻","count":2},{"name":"建筑系","count":2},{"name":"简陋","count":1},{"name":"chatgpt","count":1},{"name":"EroGēmu","count":1},{"name":"里","count":1},{"name":"根本没有NTR","count":1},{"name":"盘1","count":1},{"name":"已存","count":1},{"name":"盘3","count":1},{"name":"2013-04","count":1},{"name":"GPT机翻","count":1},{"name":"画风好","count":1},{"name":"AVG","count":1},{"name":"CG","count":1},{"name":"エルフ","count":1}]}
24-07 21:39:54.896|DEBUG|Bangumi#Bangumi:subject is {"Name":"麻呂の患者はガテン系（麻吕的患者是蓝领）","Description":"","CommunityScore":68,"CoverImage":{"HasContent":false,"HasImageData":true,"FileName":"70716_Z0uex.jpg","Content":null,"Path":"https://lain.bgm.tv/pic/cover/l/d6/c2/70716_Z0uex.jpg"},"BackgroundImage":{"HasContent":false,"HasImageData":true,"FileName":"70716_Z0uex.jpg","Content":null,"Path":"https://lain.bgm.tv/pic/cover/l/d6/c2/70716_Z0uex.jpg"},"Developers":[],"Genres":[],"Links":[{"Name":"Bangumi","Url":"https://bgm.tv/subject/70716"}],"Publishers":[],"ReleaseDate":{"ReleaseDate":"2013-4-25"},"Tags":[{"Name":"ELF"},{"Name":"NTR"},{"Name":"galgame"},{"Name":"土天冥海"}],"AgeRating":[],"Platform":[]}, GetBangumiMetadata returned
24-07 21:39:54.896|DEBUG|Bangumi#Bangumi:{"Name":"麻呂の患者はガテン系（麻吕的患者是蓝领）","Description":"","CommunityScore":68,"CoverImage":{"HasContent":false,"HasImageData":true,"FileName":"70716_Z0uex.jpg","Content":null,"Path":"https://lain.bgm.tv/pic/cover/l/d6/c2/70716_Z0uex.jpg"},"BackgroundImage":{"HasContent":false,"HasImageData":true,"FileName":"70716_Z0uex.jpg","Content":null,"Path":"https://lain.bgm.tv/pic/cover/l/d6/c2/70716_Z0uex.jpg"},"Developers":[],"Genres":[],"Links":[{"Name":"Bangumi","Url":"https://bgm.tv/subject/70716"}],"Publishers":[],"ReleaseDate":{"ReleaseDate":"2013-4-25"},"Tags":[{"Name":"ELF"},{"Name":"NTR"},{"Name":"galgame"},{"Name":"土天冥海"}],"AgeRating":[],"Platform":[]}
24-07 21:39:54.896|DEBUG|Bangumi#Bangumi:available fields:Name,CommunityScore,CoverImage,BackgroundImage,Links,ReleaseDate,Tags``

刮了好几次，确实是刮不出简介。

**Comment by Ivanlon30000** [comment]
bangumi上该条目简介为空：[麻呂の患者はガテン系](https://bgm.tv/subject/70716)，
因此[PlayniteBangumiMetadata](https://github.com/Ivanlon30000/PlayniteBangumiMetadata)的表现符合预期。

**Comment by X012C** [comment]
> bangumi上该条目简介为空：[麻呂の患者はガテン系](https://bgm.tv/subject/70716)， 因此[PlayniteBangumiMetadata](https://github.com/Ivanlon30000/PlayniteBangumiMetadata)的表现符合预期。

打扰了。完全没意识到数据源没信息的情况，看了一下这系列三部确实都没简介，我还挨个刮了一遍，注意力都在标签了，还想着怎么这么多内容都没刮削到简介，陷入了奇妙的思维漩涡里面了。
